services:
  - type: web
    name: hiperdiagnosa
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /api/metrics